import React from "react";

import { HStack, Text } from "@chakra-ui/react";

import { useFormContext } from "react-hook-form";

import { CreateAnAgencyFormValuesType } from "./schema";

export const AutoGeneratedAddressText = () => {
  const { watch } = useFormContext<Partial<CreateAnAgencyFormValuesType>>();

  const province = watch("province")?.at(0)?.label;
  const municipality = watch("municipality")?.at(0)?.label;
  const sector = watch("sector")?.at(0)?.label;
  const street = watch("street")?.trimEnd();
  const reference = watch("reference")?.trimEnd();

  return (
    <HStack alignItems="flex-start">
      <b>Dirección:</b>
      <Text fontFamily="mono" fontSize="sm">
        {reference && reference.concat(", ")}
        {street && street.concat(", ")}
        {sector && sector.concat(", ")}
        {municipality && municipality.concat(", ")}
        {province?.concat(".")}
      </Text>
    </HStack>
  );
};
