import React from "react";

import { HStack } from "@chakra-ui/react";

import { SimpleTextFieldController } from "@/components/atoms";
import { Option, SelectFieldController } from "@/components/organisms";
import { municipalitiesApi } from "@/store/features/api/municipalities";
import { provincesApi } from "@/store/features/api/provinces";
import { sectorsApi } from "@/store/features/api/sectors";

import { useFormContext } from "react-hook-form";

import { AutoGeneratedAddressText } from "./AutoGeneratedAddressText";

export const AddressFields = () => {
  const { setValue, getValues } = useFormContext();

  const { data: provinces } = provincesApi.useGetProvincesQuery(null);
  const [getMunicipalities, { data: municipalities }] = municipalitiesApi.useLazyGetMunicipalitiesQuery();
  const [getSectors, { data: sectors }] = sectorsApi.useLazyGetSectorsQuery();

  return (
    <div>
      <SelectFieldController
        label="Provincia"
        name="province"
        options={
          provinces?.data.provinces.map((province: any) => ({ label: province.name, value: province._id })) || []
        }
        onChange={(values) => {
          const value = values.at(0);
          if (!value) return;

          setValue("municipality", null);
          getMunicipalities({ provinceId: value.value });
        }}
      />
      <HStack alignItems="flex-start" spacing="4">
        <SelectFieldController
          label="Municipio"
          name="municipality"
          options={
            municipalities?.data.municipalities.map((municipality: any) => ({
              label: municipality.name,
              value: municipality._id,
            })) || []
          }
          onChange={(values) => {
            const value = values.at(0);
            if (!value) return;
            const province: Option[] = getValues("province");
            getSectors({ municipalityId: value.value, provinceId: province[0].value });
          }}
        />
        <SelectFieldController
          label="Sector"
          name="sector"
          options={
            sectors?.data.sectors.map((sector: any) => ({
              label: sector.name,
              value: sector._id,
            })) || []
          }
        />
      </HStack>
      <SimpleTextFieldController label="Calle" name="street" placeholder="Ingresa la referencia" />
      <SimpleTextFieldController label="Referencía" name="reference" placeholder="Ingresa la referencia" />
      <AutoGeneratedAddressText />
    </div>
  );
};
