import React from "react";

import { HStack, Text } from "@chakra-ui/react";

import { useFormContext } from "react-hook-form";

import { RegisterAgencyFormType } from "./schema";

export const AutoGeneratedAddressText = () => {
  const { watch } = useFormContext<Partial<RegisterAgencyFormType>>();

  const province = watch("province")?.at(0)?.label;
  const municipality = watch("municipality")?.at(0)?.label;
  const reference = watch("reference")?.trimEnd();

  return (
    <HStack alignItems="flex-start">
      <b>Dirección:</b>
      <Text fontFamily="mono" fontSize="sm">
        {/* Av. Gustavo Mejia Ricart esq. Defillo,  */}
        {reference ? reference.concat(municipality || province ? ", " : "") : undefined}
        {municipality ? municipality.concat(province ? ", " : "") : undefined} {province}
      </Text>
    </HStack>
  );
};
