import React, { useMemo } from "react";

import { HStack, Text } from "@chakra-ui/react";

import { useFormContext } from "react-hook-form";

import { RegisterAgencyFormType } from "./schema";

export const AutoGeneratedAddressText = () => {
  const { getValues } = useFormContext<RegisterAgencyFormType>();

  const municipality = useMemo(() => {
    const value = getValues("municipality");

    console.log(value);
  }, [getValues("municipality")]);

  return (
    <HStack alignItems="flex-start">
      <b>Dirección:</b>
      <Text fontFamily="mono" fontSize="sm">
        Av. Gustavo Mejia Ricart esq. Defillo, Puñal, Santiago de los Caballeros
      </Text>
    </HStack>
  );
};
