import React, { FC } from "react";

import { FormComponentProps } from "@atmk/components";

import { HStack } from "@chakra-ui/react";

import { SimpleTextFieldController, SubmitButton } from "@/components/atoms";
import { SelectFieldController } from "@/components/organisms";

import { useFormProvider } from "@/hooks/useFormProvider";

import { AutoGeneratedAddressText } from "./AutoGeneratedAddressText";
import { RegisterAgencyFormType, resolver } from "./schema";

interface CreateAnAgencyFormProps extends FormComponentProps<RegisterAgencyFormType> {}
export const CreateAnAgencyForm: FC<CreateAnAgencyFormProps> = ({ onSubmit, defaultValues }) => {
  const { FormProvider } = useFormProvider<RegisterAgencyFormType>({ resolver, defaultValues });

  return (
    <FormProvider onSubmit={onSubmit}>
      <SimpleTextFieldController isRequired label="Nombre" name="name" placeholder="Ingresa el nombre de tu agencia" />
      <SimpleTextFieldController isRequired label="Eslogan" name="slogan" placeholder="Ingresa el eslogan" />
      <SelectFieldController label="Provincia" name="province" options={[]} />
      <HStack alignItems="flex-start" spacing="4">
        <SelectFieldController label="Municipio" name="municipality" options={[]} />
        <SelectFieldController label="Sector" name="sector" options={[]} />
      </HStack>
      <SimpleTextFieldController label="Calle" name="street" placeholder="Ingresa la referencia" />
      <SimpleTextFieldController label="Referencía" name="reference" placeholder="Ingresa la referencia" />
      <AutoGeneratedAddressText />
      <SubmitButton colorScheme="primary" mt="4">
        Validar datos de la agencia
      </SubmitButton>
    </FormProvider>
  );
};
